### ISSUE TITLE
Questions about layer-wise sliding window attention

### ISSUE THREAD

**Issue by NormXU** [mistralai/mistral-src#40]
Thank you for the awesome work! 

I am reaching out to seek further clarity regarding the Sliding Window Attention (SWA) mechanism as described in the README

As we know, SWA is typically implemented by sliding a fixed-size window over the input sequence to process it in smaller, manageable chunk.  Suppose the window size $W$ is 5, the context length is 15 and  the decoder model has 10 layers. From my understanding, since the SWA in mistral-7B is layer-wise, in this scenario it could work as follow:

1. Initially, the window covers tokens 1 to 5 of the input sequence.
2. If the window slides by  $W-1 = 4$ tokens, it would then cover tokens 5 to 9.
3. In the next slide, it covers tokens 9 to 13.
4. Finally, it would cover tokens 11 to 15.

But this only accounts for first 4 layers out of 10 layers. I am curious about the remaining 6 layers. Do the rest layers only conduct attention mechanism on token 11 to 15?

Besides, I couldn't find any code that is about the implementation of a layer-wise sliding window. It seems that every layer uses a consistent sliding window, rather than each layer moving by W tokens. Did I miss something?

**Comment by NormXU** [comment]
@timlacroix Thank you for your reply. 
According to the README,

> At each attention layer, information can move forward by W tokens at most: after two attention layers, information can move > forward by 2W tokens, etc. For instance in a sequence of length 16K and a sliding window of 4K, after 4 layers, information > has propagated to the full sequence length.

This is where I am really confused. If my understanding is correct, the attention mechanism here is a "layer-wise" approach, which differs from the  common one we are familiar with, since a sequence of 16k length can process through 4 layers with a sliding window of 4k.

**Comment by KerfuffleV2** [comment]
@NormXU Sorry to bug you, but did you actually manage to figure out the answer to this or did you just eventually give up on ever receiving an answer?

**Comment by KerfuffleV2** [comment]
@NormXU Thank you so much for the in-depth explanation, it is very much appreciated! I know `llama.cpp` has been looking to implement this but it didn't seem like the necessary information was available.

I'll share this in the discussion over there and I'm sure it will help a lot!

**Comment by defdet** [comment]
@NormXU Hey, sorry for a bit of necroposting. I'm also trying to understand this caching idea and I think you're right about the general idea but wrong about the details. If we look at the illustration from [Mistral paper](https://arxiv.org/pdf/2310.06825.pdf):
![illustrationl](https://github.com/mistralai/mistral-src/assets/116446387/d2f31d82-baa2-4452-8eba-2e38eb60e335)
We can see here that token at the position i attends to the **maximum**  number of tokens i-w:i from the previous layer (each token only sees previous layer's tokens on the left side). At **minimum** (if i=0), it's gonna attend to only one token at position i=0 of previous layer. If we follow your example, it would mean:
The output of Layer 1 (A', B'.... are the corresponding hidden states):
A' integrates information from **only** A.
B' integrates from A, B.
C' integrates from A, B, C 
D' integrates from B, C, D (we reach the window size of 3) and so on.
And because of the stacked nature of decoder layers, tokens can attend to other tokens outside window size.
I might absolutely be wrong, but that's how it looks from the Mistral paper.

**Comment by NormXU** [comment]
@defdet Thank you for pointing this out. I think you are right. All tokens only consider information from their preceding tokens, rather than having a bi-directional attention. This makes sense to me :)

**Comment by rshah918** [comment]
Sorry for reviving this thread again haha.

I'm slightly confused on the inputs to each layer. Let's say your context vector length is 10, and each multi-head-attention layer has an input size of 5. Does layer 1 read tokens 1-5, and layer 2 takes in tokens 6-10? and each token in layer 2 attends to the tokens in layer 1, as per the diagram in the Mistral paper? @NormXU @defdet

**Comment by defdet** [comment]
@rshah918, you are correct about the whole idea, but I think you're a bit wrong about the details. Attention windows should be overlapping, as shown in the diagram above. In your example it would mean (first token is number 1, not 0) first layer indeed reads tokens 1-5, but the second one reads tokens 5-9, not 6-10. This detail is actually really important, because token 5 has information about tokens 4-1. If we don't include him in the calculations, upper layers (2 and above) are gonna have no information about tokens 4-1. Also, I'm pretty sure we're talking about whole decoder layers (consisting of self-attention and MLP each), not only attention layers.
Come to think of it, attention layers are overlapping by only one token. Maybe it could be beneficial to make them overlap by 2 tokens?..

**Comment by rshah918** [comment]
Firstly, I want you to know that I really appreciate your super quick and detailed reply!!!

Could you clarify what the query and keys would be in this example? I was under the impression that, for layer 2, Q would be tokens 5-9, and the Key would be tokens 1-5 (AKA layer 2 attends to tokens in layer 1).

**Comment by matrixssy** [comment]
> > @defdet Firstly, I want you to know that I really appreciate your super quick and detailed reply!!!
> > Could you clarify what the query and keys would be in this example? I was under the impression that, for layer 2, Q would be tokens 5-9, and the Key would be tokens 1-5 (AKA layer 2 attends to tokens in layer 1).
> 
> Hey, Bro, I have seen the implementation of mistral from github and I try to help you understand the process. First of all you have to understand that this model (mistral) has multi-layers(actually 32 layers) and the **role of each layer of cache**: mistral each layer has a cache to store the input value of this layer (actually the output value from the previous layer) that was input by the previous fragment.
> 
> After understanding what I said above, consider the example in the paper illustration: ![292238819-d2f31d82-baa2-4452-8eba-2e38eb60e335](https://private-user-images.githubusercontent.com/21152077/309308520-362d3c7a-25a3-4444-ac87-8f5b05444973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjc2NTQsIm5iZiI6MTcxMzI2NzM1NCwicGF0aCI6Ii8yMTE1MjA3Ny8zMDkzMDg1MjAtMzYyZDNjN2EtMjVhMy00NDQ0LWFjODctOGY1YjA1NDQ0OTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDExMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMjM4NDVlNTYwYjMxZDY1OGY3YTg1NjUzMzlhOTU3NTU2Mzc1NTE3NzliOWE5OGEwZTAwNzYxNzQ0YWU4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JNz4ZVf-8YTnh0O6Jdi-jwZvKjFw6yr3dZ5PIi7lvb4)
> 
> The actual expression of the second layers in the figure is that when the input is to the second fragment token 5-9, the query is actually from the current input token 5-9, while the key and value are converted to 1-9 by cache splicing token 1-5 of the previous fragment. Due to the **slide window size** set (4 for example), each token can only see the previous 4 furthest tokens. At the same time, in the attention calculation process of this layer, token 9 in token 5-9 in the same fragment can see the information of token 5 at the farthest. In this way, layer 2 token 9 indirectly sees layer1 token 1 information through layer 2 token 5. And so on, assume that the slide window size is W, and assume that the token entered in the position T on this layer can see the token from the position T-W on the previous layer.

Actually, I have also looked at their implemented source code, and I'm curious that SWA cannot be applied to training.

**Comment by defdet** [comment]
It doesn't matter anyway lol. Mistral v2 doesn't have SWA.

**Comment by developerlin** [comment]
It is not related to mask , every layer has the same window, no shift. I have deep discussion w/ GPT4 about this topic, finally it is clear now, see the below GPT4 explains. 

--
When we discuss how multi-layer stacking allows models to integrate broader contextual information in deeper layers, we are describing a recursive information processing mechanism. In this mechanism, each layer not only processes the input it directly receives but also indirectly integrates information from previous layers. This recursive layering is a core feature of deep learning and particularly deep Transformer models, enabling the capture and utilization of long-range data dependencies.

**Layer-by-layer Information Accumulation**

Each layer's output contains information processed by that layer as well as information inherited from its input. This means that although each token may only directly attend to the previous W−1 tokens' information at each layer, through inter-layer transmission, each layer can indirectly access information processed by earlier layers.

**Specific Example**

Consider a simple example with a window size W=4 and a model with three layers. Here's how Token 5 can access a broader range of information at each layer:

- First Layer: Token 5 directly attends to Tokens 2, 3, 4, and itself.
- Second Layer: At this layer, Token 5 again attends to Tokens 2, 3, 4, and itself. However, since these tokens have already aggregated information from their preceding tokens in the first layer, Token 5 now indirectly accesses information from Token 1 (through Token 2).
- Third Layer: The process repeats, and Token 5 continues to attend to Tokens 2, 3, 4, and itself, but these tokens now contain aggregated information from even further tokens (like Token 1). Thus, by the third layer, Token 5 can indirectly aggregate information from Tokens 1, 2, 3, and 4.

**Indirect Receptive Field Expansion**

With each layer, Token 5’s indirect receptive field expands. Although the direct computation window per layer is fixed, the layer-by-layer transmission of information allows each token to 'see' the influence of increasingly distant other tokens. This layer-wise expansion of the receptive field enables deep networks to handle complex, long-range dependencies, which is particularly important in natural language processing, image processing, and other scenarios.

**Conclusion**

Multi-layer stacked networks achieve the recognition of complex patterns and the capture of long-range dependencies through the accumulation and transformation of information across layers. This capability is a key feature distinguishing deep learning models, especially Transformer-type models, from shallow models, critically supporting their efficient performance on various complex tasks.
